// Every word on the page, in Chinese (the default) and English.

export const PORTS = [
    { code: 'ME-CL', cn: ['水星', '卡路里港'], en: ['Mercury', 'Caloris Port'] },
    { code: 'V-IS', cn: ['金星', '伊什塔尔浮城'], en: ['Venus', 'Ishtar Aerostat'] },
    { code: 'E-SH', cn: ['地球', '上海星港'], en: ['Earth', 'Shanghai Spaceport'] },
    { code: 'M-HZ', cn: ['火星', '视界星港'], en: ['Mars', 'Horizon Starport'] },
    { code: 'C-CR', cn: ['谷神星', '谷神星矿港'], en: ['Ceres', 'Ceres Mining Port'] },
    { code: 'J-CA', cn: ['木星', '木卫四港'], en: ['Jupiter', 'Callisto Port'] },
    { code: 'S-TI', cn: ['土星', '土卫六港'], en: ['Saturn', 'Titan Port'] },
    { code: 'U-TT', cn: ['天王星', '天卫三站'], en: ['Uranus', 'Titania Station'] },
    { code: 'N-TR', cn: ['海王星', '海卫一站'], en: ['Neptune', 'Triton Station'] },
];

export const SHIPS = [['复兴号', 'Renaissance'], ['天问号', 'Tianwen'], ['祝融号', 'Zhurong'], ['鹊桥号', 'Queqiao'],
    ['夸父号', 'Kuafu'], ['羲和号', 'Xihe'], ['望舒号', 'Wangshu'], ['精卫号', 'Jingwei']];

export const TEXT = {
    cn: {
        eyebrow: '太阳系星港 · 航班与物流查询',
        h1: '从这里出发，去太阳系的任何一个港口',
        lede: '拖动星图看行星此刻的位置，点两颗行星查询航线：下一个发射窗口、航程、运价和信号延时，然后领取你的登机牌。',
        sky: '星图', compressed: '压缩比例', trueScale: '真实比例',
        legend: '拖动旋转 · 点击行星设为出发地或目的地', play: '▶ 快进', pause: '❚❚ 暂停', story: '故事时间', real: '现实',
        desk: '行程查询', from: '出发', to: '到达', swap: '对调出发和到达',
        pax: '乘客', cargo: '货运', msg: '只发消息', mass: '货物质量（公斤）', speed: '速度等级',
        eco: '经济', exp: '快线', torch: '急行',
        ecoW: '最省燃料的航线，所以要等窗口。', expW: '更快的航线，四个月内出发，燃料更多。', torchW: '几乎直线冲刺，给急件和急需的人。六周内出发，费用贵很多倍。',
        msgW: '这是光走单程的时间。一问一答要再翻一倍。', same: '出发地和目的地是同一个港口。',
        dist: '此刻距离', mkm: '百万公里', lag: '此刻信号延时', window: '下一个发射窗口', open: '窗口开放中',
        tof: '航程', dv: 'Δv', path: '飞行距离', fare: '票价', freight: '运费', days: '天', min: '分钟',
        book: '领取登机牌', ping: '发一条消息', sent: '消息已发出，抵达还需 ',
        arrival: '到港服务台', marsTime: '火星协调时', sol: '火星日', facilities: '火星开放设施',
        facLink: '全部设施', mapLink: '火星地图', hubLink: '太空企业招聘', soon: '此港口的到港服务即将开放。', noData: '设施数据暂时读不到。',
        status: { operating: '运行', reduced: '降负荷', maintenance: '检修', offline: '停机' },
        board: '出发航班', boardNote: '按出发时间排序 · 故事时间',
        flight: '航班', ship: '飞船', route: '航线', departs: '出发', duration: '航程', state: '状态',
        boarding: '登机中', ontime: '准点', waiting: '等待窗口',
        inflight: '在途飞船',
        pass: '星际旅行登机牌', org: '星际移民中心', passenger: '乘客', gate: '站台', arrives: '到达', deck: '甲板', room: '舱房',
        name: '你的名字', namePh: '写在登机牌上的名字', stamps: '印章', copy: '复制分享链接', close: '收好了', copied: '链接已复制',
        tools: '小工具', now: '回到此刻', share: '复制本航线链接', myStamps: '我的印章', noStamps: '还没有印章，领一张登机牌就有了。',
        conv: '现实日期换算', convNote: '换算成故事年份和火星日', toc: '目录', link: '地火链路', clear: '通畅', degraded: '日凌降级',
        skip: '跳到正文',
    },
    en: {
        eyebrow: 'Solar Port · flights and freight',
        h1: 'Leave from here for any port in the solar system',
        lede: 'Drag the sky to see where the planets are right now. Pick two of them to see the next launch window, flight time, fare and signal delay, then collect your boarding pass.',
        sky: 'Sky', compressed: 'Compressed', trueScale: 'True scale',
        legend: 'Drag to turn · click a planet to set origin or destination', play: '▶ Fast-forward', pause: '❚❚ Pause', story: 'Story', real: 'Real',
        desk: 'Trip inquiry', from: 'From', to: 'To', swap: 'Swap origin and destination',
        pax: 'Passenger', cargo: 'Freight', msg: 'Message only', mass: 'Cargo mass (kg)', speed: 'Speed class',
        eco: 'Economy', exp: 'Express', torch: 'Torch',
        ecoW: 'The route that uses the least fuel, so it waits for the window.', expW: 'A faster route. Leaves within four months and burns more fuel.', torchW: 'A near-straight dash for urgent cargo and people. Leaves within six weeks and costs many times more.',
        msgW: 'Light takes this long one way. A question and its answer take twice as long.', same: 'Origin and destination are the same port.',
        dist: 'Distance now', mkm: 'million km', lag: 'Signal delay now', window: 'Next launch window', open: 'Window open',
        tof: 'Flight time', dv: 'Δv', path: 'Distance flown', fare: 'Fare', freight: 'Freight cost', days: 'days', min: 'min',
        book: 'Get boarding pass', ping: 'Send a message', sent: 'Message sent. It arrives in ',
        arrival: 'Arrival desk', marsTime: 'Mars Coordinated Time', sol: 'Sol', facilities: 'Mars Open Facilities',
        facLink: 'All facilities', mapLink: 'Map of Mars', hubLink: 'Space companies hiring', soon: 'Arrival services for this port open soon.', noData: 'Facility data cannot be reached right now.',
        status: { operating: 'Operating', reduced: 'Reduced', maintenance: 'Maintenance', offline: 'Offline' },
        board: 'Departures', boardNote: 'By departure · story time',
        flight: 'Flight', ship: 'Ship', route: 'Route', departs: 'Departs', duration: 'Flight time', state: 'Status',
        boarding: 'Boarding', ontime: 'On time', waiting: 'Awaiting window',
        inflight: 'Ships in flight',
        pass: 'Interplanetary boarding pass', org: 'Interplanetary Immigration Center', passenger: 'Passenger', gate: 'Platform', arrives: 'Arrives', deck: 'Deck', room: 'Cabin',
        name: 'Your name', namePh: 'Name on the boarding pass', stamps: 'Stamps', copy: 'Copy share link', close: 'Got it', copied: 'Link copied',
        tools: 'Tools', now: 'Back to now', share: 'Copy this route link', myStamps: 'My stamps', noStamps: 'No stamps yet. Collect a boarding pass to get one.',
        conv: 'Convert a real date', convNote: 'to its story year and Mars sol', toc: 'Contents', link: 'Earth–Mars link', clear: 'clear', degraded: 'conjunction',
        skip: 'Skip to content',
    },
};
